# Core Colors
background            #13140c
foreground            #e5e3d6
selection_foreground  #c6cc7a
selection_background  #2f3300
cursor                #c6cc7a
cursor_text_color     #13140c

# Regular Colors
color0  #13140c
color1  #ffb4ab
color2  #c6cc7a
color3  #a3d0c0
color4  #e2e993
color5  #e4e5c1
color6  #c8c9a6
color7  #e5e3d6

# Bright Colors
color8  #3a3a31
color9  #ffb4ab
color10 #c6cc7a
color11 #a3d0c0
color12 #e2e993
color13 #e4e5c1 
color14 #c8c9a6
color15 #e5e3d6
