# Core Colors
background            #16130b
foreground            #eae1d4
selection_foreground  #e5c36c
selection_background  #3e2e00
cursor                #e5c36c
cursor_text_color     #16130b

# Regular Colors
color0  #16130b
color1  #ffb4ab
color2  #e5c36c
color3  #aecfac
color4  #ffdf92
color5  #f3e1bb
color6  #d6c5a0
color7  #eae1d4

# Bright Colors
color8  #3d392f
color9  #ffb4ab
color10 #e5c36c
color11 #aecfac
color12 #ffdf92
color13 #f3e1bb 
color14 #d6c5a0
color15 #eae1d4
