# Core Colors
background            #19120c
foreground            #efe0d5
selection_foreground  #fdb876
selection_background  #4a2800
cursor                #fdb876
cursor_text_color     #19120c

# Regular Colors
color0  #19120c
color1  #ffb4ab
color2  #fdb876
color3  #c1cc99
color4  #ffdcbf
color5  #ffdcbf
color6  #e2c0a4
color7  #efe0d5

# Bright Colors
color8  #403830
color9  #ffb4ab
color10 #fdb876
color11 #c1cc99
color12 #ffdcbf
color13 #ffdcbf 
color14 #e2c0a4
color15 #efe0d5
